CREATE TABLE USUARIO (
    ID_USUARIO NUMBER NOT NULL ENABLE, 
    NOMBRE VARCHAR2(15) NOT NULL ENABLE, 
    CLAVE VARCHAR2(10) NOT NULL ENABLE, 
    NIVEL VARCHAR2(10) NOT NULL ENABLE, 
    FECHA_CREACION DATE, 
    FECHA_MODIFICACION DATE, 
	CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO) ENABLE
);

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER NOT NULL ENABLE, 
    NOMBRE VARCHAR2(30), 
    CIF VARCHAR2(14), 
    DIRECCION VARCHAR2(30), 
    LOCALIDAD VARCHAR2(20), 
    PROVINCIA VARCHAR2(20), 
    FECHA_CREACION DATE, 
    FECHA_MODIFICACION DATE, 
	CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE) ENABLE
);

CREATE TABLE ARTICULO (
    ID_ARTICULO NUMBER NOT NULL ENABLE, 
    NOMBRE VARCHAR2(30) NOT NULL ENABLE, 
    PRECIO NUMBER(6,3), 
    FECHA_CREACION DATE, 
    FECHA_MODIFICACION DATE, 
	CONSTRAINT ARTICULO_PK PRIMARY KEY (ID_ARTICULO) ENABLE
);

CREATE TABLE CABECERA (
    NUMERO NUMBER NOT NULL ENABLE, 
    FECHA VARCHAR2(10) NOT NULL ENABLE, 
    ID_CLIENTE NUMBER NOT NULL ENABLE, 
    ID_USUARIO NUMBER NOT NULL ENABLE, 
    FECHA_CREACION DATE, 
    FECHA_MODIFICACION DATE, 
	CONSTRAINT CABECERA_PK PRIMARY KEY (NUMERO, FECHA) ENABLE, 
	CONSTRAINT CABECERA_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ENABLE, 
	CONSTRAINT CABECERA_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ENABLE
);

CREATE TABLE DETALLE (
    NUMERO NUMBER(11,0) NOT NULL ENABLE, 
    FECHA VARCHAR2(10) NOT NULL ENABLE, 
    ORDEN NUMBER(11,0) NOT NULL ENABLE, 
    ID_ARTICULO NUMBER(11,0), 
    BULTOS NUMBER(4,0), 
    CANTIDAD NUMBER(4,0), 
    PRECIO NUMBER(6,2), 
    FECHA_CREACION DATE, 
    FECHA_MODIFICACION DATE, 
	CONSTRAINT DETALLE_PK PRIMARY KEY (NUMERO, FECHA, ORDEN) ENABLE, 
	CONSTRAINT CABECERA_DETALLE_FK FOREIGN KEY (NUMERO, FECHA) REFERENCES CABECERA (NUMERO, FECHA) ENABLE, 
	CONSTRAINT ARTICULO_DETALLE_FK FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO) ENABLE
);
